### ISSUE TITLE
Engine performance isn't synced with era

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#403]
Title, seems like it uses Early-WW2 engine stats and rolling resistance, but with Late-WW2 limits (max displacement and cylinders).

**Comment by SprocketTools** [comment]
I was able to get more concrete information related to this bug.  I guess https://sprockettools.github.io/TopGearCalculator.html has paid off!
First I'll add a note that the "horsepower at given RPM" slider is always correct to the vehicle era.

When making a new design while the slider is set to Late WWII:
- engine limits match late WWII
- performance matches interwar tech

When making a new design while the slider is set to Early WWII:
- engine limits match early WWII
- performance matches interwar tech

When making a new design while the slider is set to WWI:
- engine limits match WWI
- performance matches WWI

Note that changing the vehicle era after creating the vehicle does pretty much nothing to the tank.

**Comment by Muushy** [comment]
Fixed in V0.2 CBT 2

**Comment by SprocketTools** [comment]
Engine performance bug (while driving the vehicle around) still seems to be there.  All of the sliders are correct, but the actual performance itself still matches interwar or WWI depending on the era you have picked.

**Comment by DarioXN** [comment]
> Engine performance bug (while driving the vehicle around) still seems to be there. All of the sliders are correct, but the actual performance itself still matches interwar or WWI depending on the era you have picked.

**Comment by Muushy** [comment]
Era tech loading using a new system which should prevent stuff like this from happening again.

**Comment by SprocketTools** [comment]
Bug is still present.  Using https://sprockettools.github.io/TopGearCalculator.html as a reference, engines perform similar to what it predicts when era is set to Interwar.

**Comment by DarioXN** [comment]
> Bug is still present. Using https://sprockettools.github.io/TopGearCalculator.html as a reference, engines perform similar to what it predicts when era is set to Interwar.

**Comment by DarioXN** [comment]
Marked as major bug as this also interferes with trying to build reasonable designs, as it takes mobility out of the equation.

**Comment by Muushy** [comment]
Track rolling resistance wasn't being applied and a constant fallback value was being used.
Fixed in V0.2 Closed Alpha B1.
